databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: app-backend
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: web
    name: app-frontend
    branch: master
    runtime: static
    buildCommand: "cd frontend && npm install"
    startCommand: "npm run webpack"
    staticPublishPath: ./frontend/build/
    # Build and deploy `app-frontend` if any `js` file changes,
    # but ignore any test files.
    buildFilter:
      paths:
      - frontend/**/*.js
      ignoredPaths:
      - frontend/**/*.test.js  
